### ISSUE TITLE
GameServerConfig error

### ISSUE THREAD

**Issue by kaizawat** [LeagueSandbox/GameServer#1015]
![image](https://user-images.githubusercontent.com/70490920/93803574-c241e080-fc4d-11ea-9fe9-fb239df5629c.png)

I'm having an error like this, i've tried everything I could do and I couldn't make any progress at all.. My Visual Studio experience is literally zero and I don't know it at all..

**Comment by danil179** [comment]
The error is self explanatory: https://en.wikipedia.org/wiki/Escape_character#Examples

**Comment by danil179** [comment]
Close this. Consider adding it to a wiki FAQ.
