### ISSUE TITLE
Windows incompatibility

### ISSUE THREAD

**Issue by lzardy** [LeagueSandbox/GameServer#1029]
Due to #979, running GameServerConsole on Windows with Any CPU as the target platform causes the error:

`Exception thrown: 'System.BadImageFormatException' in ENetCS.dll
An unhandled exception of type 'System.BadImageFormatException' occurred in ENetCS.dll
An attempt was made to load a program with an incorrect format. (0x8007000B)`

Reverting the commit fixes the issue (setting the target platform back to x86).
However, if we want to support both Windows and Linux, we'd need a different solution.

**Comment by danil179** [comment]
There are the x64 dlls in other project that should be copied with the corresponding NuGet. Since we do not have access to that NuGet anymore, we need to devise another solution.

**Comment by microsoftv** [comment]
> There are the x64 dlls in other project that should be copied with the corresponding NuGet. Since we do not have access to that NuGet anymore, we need to devise another solution.

**Comment by lzardy** [comment]
Resolved via #1030 (although only partially).

**Comment by MythicManiac** [comment]
@danil179 the NuGet is under my account FWIW
