### ISSUE TITLE
Buffs and debuffs are removed on player move

### ISSUE THREAD

**Issue by cntseesharp** [LeagueSandbox/GameServer#1035]
#1011 Broke all buffs, they are disabled on player move, issue is Buff.cs, lines: 84-89

**Comment by danil179** [comment]
I'm not sure about that. These lines of code are needed for the case of `Recall` buff. There is a general flag for each spell `OriginSpell.SpellData.CantCancelWhileChanneling` that should indicate if the buff is cancelled upon move and so. Please indicate what buffs exactly do not work with it so I can further check into this.

I assume that there are problems with the data itself for some buffs, but very generally it should be fairly OK.

**Comment by danil179** [comment]
Related #1019

**Comment by lzardy** [comment]
Although not a focus at the moment, for later, these kinds of things are what we want to avoid when it comes to event handling:
[Buff.cs Line 121](https://github.com/LeagueSandbox/GameServer/blob/indev/GameServerLib/GameObjects/Spells/Buff.cs#L121)

Events are capable of being hooked by scripts individually (along with a callback function), wherein each of the scripts and their callback function are called when the event occurs. Listeners should _never_ be created outside of a script instance (that includes OnUpdate, as it should be called via the script's Owner.Update).

**Comment by lzardy** [comment]
Resolved by #1267
