### ISSUE TITLE
ReloadScripts command always throws

### ISSUE THREAD

**Issue by indiemini** [LeagueSandbox/GameServer#1040]
The `!reloadscripts` command will always throw an error, since we try to add duplicate entries to the scripting engine's dictionary.
https://github.com/LeagueSandbox/GameServer/blob/183b5ee68866cf37f5b1091f81b5e5dba07145b5/GameServerLib/Scripting/CSharp/CSharpScriptEngine.cs#L105-L115

Changing this line from:
```cs
types.Add(type.FullName, type);
```
to:
```cs
types[type.FullName] = type;
```

should do the trick.

Once this is fixed, it would probably also be a good idea to refresh the spell + buff data still held in memory (i.e. your champion may hold a reference to a script that was compiled BEFORE the reload), but a second issue can be opened for this.

**Comment by lzardy** [comment]
If a PR is made for this, the author should also keep in mind this issue since it is related: #723
