### ISSUE TITLE
Flash slide bug

### ISSUE THREAD

**Issue by danil179** [LeagueSandbox/GameServer#1061]
Flash displays "sliding" animation towards the end point on the following occasions:
1. Flashing into unwalkable terrain.
2. Flashing in the near proximity of the character (the mouse cursor almost identically lies on the player).

**Comment by cabeca1143** [comment]
Another flash slide problem just found is when you cap your fps to anything bellow 125fps, it makes you slide even if the cursor is far from the character.

It's a gradual change, while 125fps gives you consistent flash teleport, 120fps gives a ~3/5 ratio of teleporting, and lowering to 115 lowers that chance to what i'd say ~1/(5 or 6).

It is also the same source to the problem in #1065, so uncapping or playing above 125fps also solves the duping item problem
