### ISSUE TITLE
! Chat commands not publishing ChatMessageRequest 

### ISSUE THREAD

**Issue by davidivkovic** [LeagueSandbox/GameServer#1072]
Typing !ad 100, or any other !command in the chat box, does not trigger the `new HandleChatBoxMessage(this).HandlePacket` in [Game.cs](https://github.com/LeagueSandbox/GameServer/blob/286a358681ba2c3a9bf683591933f2e2393bb65a/GameServerLib/Game.cs#L207)

**Comment by danil179** [comment]
@microsoftv Did your PR #1069 solved this issue?

**Comment by lzardy** [comment]
Seems it has not.

**Comment by danil179** [comment]
@microsoftv I think your LoadScreen PR disabled all LoadScreen packets. I'll try to solve it, but meanwhile it may be better to just revert the changes,
