### ISSUE TITLE
!reloadscripts does not work as expected

### ISSUE THREAD

**Issue by davidivkovic** [LeagueSandbox/GameServer#1075]
!reloadscripts does not reload scripts with the new scripting API.

Logger logs: DEBUG LeagueSandbox.GameServer.Content.Package - Loaded all C# scripts from package: LeagueSandbox-Scripts from [here](https://github.com/LeagueSandbox/GameServer/blob/7efead4ca12e9220b7a54544fc22bdc648865c05/GameServerLib/Content/Package.cs#L174)
but the scripts are not reloaded until relaunching the GameServer.

For example, modifying [LeagueSandbox-Scripts/Champions/Ezreal/Q.cs](https://github.com/LeagueSandbox/GameServer/blob/indev/Content/LeagueSandbox-Scripts/Champions/Ezreal/Q.cs) , saving the file, and then using !reloadscripts does not reload the changes into the game.

The only way to "hot reload" changes is to swap to another champion and back, which is buggy, requires leveling again, and sometimes breaks spell casting.

**Comment by lzardy** [comment]
The command has just about never worked, or at least broke very soon after being implemented.

**Comment by danil179** [comment]
Refs #1040 

Seems like spell and buff data need to be refreshed after scripts have been recompiled.

**Comment by davidivkovic** [comment]
[This piece of code](https://github.com/LeagueSandbox/GameServer/blob/9d442c5efd57ae2efb9ca06f142541b4f1cdb4cf/GameServerLib/GameObjects/Spell/Spell.cs#L63-L77) should be re-run to refresh a spell? Essentially create a new instance of the script from the scriptEngine?

```
            //Set the game script for the spell

            _spellScript = _scriptEngine.CreateObject<ISpellScript>("Spells", spellName) ?? new SpellScriptEmpty();

            if (_spellScript.ScriptMetadata.TriggersSpellCasts)
            {
                ApiEventManager.OnSpellCast.AddListener(_spellScript, this, _spellScript.OnSpellCast);
                ApiEventManager.OnSpellPostCast.AddListener(_spellScript, this, _spellScript.OnSpellPostCast);
            }

            if (_spellScript.ScriptMetadata.ChannelDuration > 0)
            {
                ApiEventManager.OnSpellChannel.AddListener(_spellScript, this, _spellScript.OnSpellChannel);
                ApiEventManager.OnSpellChannelCancel.AddListener(_spellScript, this, _spellScript.OnSpellChannelCancel);
                ApiEventManager.OnSpellPostChannel.AddListener(_spellScript, this, _spellScript.OnSpellPostChannel);
            }
```

Similar code in [Buff.cs](https://github.com/LeagueSandbox/GameServer/blob/9d442c5efd57ae2efb9ca06f142541b4f1cdb4cf/GameServerLib/GameObjects/Buff.cs#L77)

**Comment by lzardy** [comment]
Not just re-ran, but also removing the previous spell script object.

**Comment by davidivkovic** [comment]
I figured it out in the meantime, the previous event listeners have to be removed too. Some discussion about this, and also the file watcher proposal from  #723.

Should we extract the mentioned code into public methods to load scripts in Spell.cs and Buff.cs?

Also, I've implemented the file watcher proposed in #723, the problem is that sometimes an access exception is thrown when the CSharpScriptEngine tries to parse the files that the watcher is watching. Any ideas how to synchronize those two?

Also another thing to discuss, removing the !reloadscripts command and replacing it with a !hotreload one?

**Comment by lzardy** [comment]
> I figured it out in the meantime, the previous event listeners have to be removed too. Some discussion about this, and also the file watcher proposal from #723.
> 
> Should we extract the mentioned code into public methods to load scripts in Spell.cs and Buff.cs?
> 
> Also, I've implemented the file watcher proposed in #723, the problem is that sometimes an access exception is thrown when the CSharpScriptEngine tries to parse the files that the watcher is watching. Any ideas how to synchronize those two?
> 
> Also another thing to discuss, removing the !reloadscripts command and replacing it with a !hotreload one?

I agree that the creation of the spell script and adding of listeners should be placed in their own function. This also goes for the removal of the spell script as well (same for buffs).

Parsing should occur before file watcher is initialized.

What would be the difference between reloadscripts and hotreload? Are you attempting to make it more generalized, where it reloads more than just scripts?

**Comment by davidivkovic** [comment]
My thought was that !hotreload 1 would enable watching the scrips for modifications and hot reloading those into the game, it would save the hassle of always typing !reloadscripts when modifying scripts, thus making it easier for newcomers to develop scripts.

That would for example be similar to the "dotnet watch run" command.

**Comment by lzardy** [comment]
Gotcha, I have no problems with that being the replacement.

**Comment by davidivkovic** [comment]
Thanks, the only thing left to solve for me is the file watcher we've discussed. Let me give you some code for clarification.

```
  ScriptsHotReloadWatcher = new FileSystemWatcher
  {
      Path = scriptsPath,
      IncludeSubdirectories = true,
      EnableRaisingEvents = true,
      NotifyFilter = NotifyFilters.LastWrite,
      Filter = "*.*",
  };
  ScriptsHotReloadWatcher.Changed += (o, ea) => LoadScripts();
```

The issue is that LoadScripts() in turn calls CSharpScriptEngine.LoadSubdirectoryScripts() which reads and parses the files that the FileSystemWatcher is watching, and that results in the exception "The process cannot access the file because it is being used by another process".

The discussion here is how to implement some sort of wait until the file is unlocked. The most popular solutions on the internet use some waiting mechanism like Task.Delay();

**Comment by lzardy** [comment]
I would first attempt to make a list or something similar of all the files changed, then attempt to remove/filter those files from the watcher before reloading. Otherwise, I'd assume a form of waiting should be fine.
