### ISSUE TITLE
League SandBox Auto Setup can't start downloading the game

### ISSUE THREAD

**Issue by artDeil4ek** [LeagueSandbox/GameServer#1088]
![2021-04-25_11-38-44](https://user-images.githubusercontent.com/62905878/115986939-78422400-a5bb-11eb-8d19-e862717e9122.png)
after 5 seconds, the program closes
I tried to download the client and put it in the directory with the sandbox, but it did not help, the same error comes out
help, ap yi is waiting for me

**Comment by danil179** [comment]
The auto setup repository is another repo.

Related LeagueSandbox/LeagueSandboxAutoSetup#7
