### ISSUE TITLE
Artifacts seem to contain wrong settings files

### ISSUE THREAD

**Issue by danil179** [LeagueSandbox/GameServer#1089]
Content path cannot be found with the artifacts settings. (There is additional "../" in the path or so).

**Comment by lzardy** [comment]
The artifact is built using AnyCPU, and the path to the content is setup for x86. This was done as a compromise as Linux utilizes AnyCPU, whereas Windows uses x86, and most users are on Windows.

Ideally we'd have an issue for AnyCPU supporting both Linux and Windows, which will solve both issues.

**Comment by fayeinmay** [comment]
@microsoftv Would anything prevent us from just using path traversal to get the Content path?

I'm actually doing this already for the game server running in docker on linux. https://paste.jandev.de/oluyocevus.cs

**Comment by lzardy** [comment]
Sure, if the file isn't found with the default path, should be fine to use traversal.
