### ISSUE TITLE
Is there anyway to add or modify the content of the LS client?

### ISSUE THREAD

**Issue by NukedBart** [LeagueSandbox/GameServer#1104]
I'm not sure about if there's a way to add or modify models, maps, champions or particles of the LS client.

**Comment by cabeca1143** [comment]
You could probably just use old custom skin tools such as wooxy without problems for simple things such as models&particles

**Comment by lzardy** [comment]
The Content is decentralized, meaning it is fully customizable (given you follow the format of the existing content).
If you make content changes to the server, you must also make the changes to the game client's content.

**Comment by fayeinmay** [comment]
Closing this as it's not an issue but rather a question. (Preferably ask questions on our Discord! :-) )
