### ISSUE TITLE
Mana stat modifier is applied again on each level up.

### ISSUE THREAD

**Issue by Ardgon** [LeagueSandbox/GameServer#1136]
Whenever a champion levels up any mana gained from items is applied again on top of already existing mana modifiers.

**Comment by danil179** [comment]
The bug is in this line:
https://github.com/LeagueSandbox/GameServer/blob/a5b69a62730804d8d3de1528e3efa284c9e7b2ad/GameServerLib/GameObjects/Stats/Stats.cs#L219

Should be applied as a modifier and not as it is now. All this function need to be fixed with modifiers.
