### ISSUE TITLE
Migrate to LEnet repo instead of the current C port

### ISSUE THREAD

**Issue by danil179** [LeagueSandbox/GameServer#1155]
This should resolve all the x65/x86 incompatibility issues and remove much of the unnecessary incompatibility issues.

This will resolve #991.

**Comment by fayeinmay** [comment]
We did this already in relation to the launcher. Can be found here: https://git.fayedev.de/leagues4/ls4-game-server

**Comment by fayeinmay** [comment]
Just basically merge this into the project: https://git.fayedev.de/leagues4/ls4-game-server/-/commit/24adbe21640c25331aaf5a0781681dd4252cd120

**Comment by juliolitwin** [comment]
Hey @JanDevDE is Enet just prototype/incomplete? Or has been made the full implementation of Enet?

**Comment by fayeinmay** [comment]
@juliolitwin That's a complete migration to LENet that I posted. Should be fully working.
