### ISSUE TITLE
Redundant line in bush logic check

### ISSUE THREAD

**Issue by danil179** [LeagueSandbox/GameServer#1170]
https://github.com/LeagueSandbox/GameServer/blob/13239cdefcdd2aa73e0b6cdfd6900d9f7ad96bf2/GameServerLib/Content/Navigation/NavigationGrid.cs#L834

Seems to be equivalent to `True=True`.

**Comment by cabeca1143** [comment]
The explanation i was given for it is:
"It is a variable initialized outside the loop, so we can store what happened in the previous loop to be used in the next one.
If the previous one had bush, then we know to use the "different bush" logic."

I still don't get it tho.

**Comment by danil179** [comment]
> 
> 
> The explanation i was given for it is:
> "It is a variable initialized outside the loop, so we can store what happened in the previous loop to be used in the next one.
> If the previous one had bush, then we know to use the "different bush" logic."
> 
> I still don't get it tho.

Entering this line requires as a precondition both `isGrass=True` and `prevPosHadBush =True`. This line is not really needed.

**Comment by cabeca1143** [comment]
Alright, I'll remove it then
