### ISSUE TITLE
Mana/Energy Consumed Multiple times on Point and Click Abilities

### ISSUE THREAD

**Issue by LornMilk** [LeagueSandbox/GameServer#1175]
If you hover on a target with a point and click ability and cast it but are out of range, it will consume the resource anyway, and then consume it again once your character has moved into range and casts the ability. If you click it multiple times it consumes the resource on each click when they are out of range. Tested on Veigar Q, Akali Q, Taric E.

**Comment by LornMilk** [comment]
Moving Too Correct Page.

**Comment by cabeca1143** [comment]
This is a general issue, you can keep it here
