### ISSUE TITLE
A collection of bugs I have experienced (some might be known)

### ISSUE THREAD

**Issue by JensGeisen** [LeagueSandbox/GameServer#1221]
I experienced that some map objects cause bugs that may be caused by the automated path finding. Also the minions, some pass out, some follow you even though they'd normally give a sh#t when u'd get away from them about a certain distance
what i have mostly noticed (beside minions)

Casting spells on targets that are out of range, consumes mana / energy. You can cast it endlessly until you dont have mana left. if you then right click on a champ, it will use the ability that you pressed when you were out of range
yeah, I had that. In newer versions the range is shown and it doesn't affect your mana when someone is out of range. Beside that it's possible that out of range isn't measured at the time you click but at a certain range of time
And also, Mana pots dont work. Idk why but they literally didnt affect my mana gain at all (as far as i noticed it)
Another probleme is that champions can't run through the minions  or other champions. That's an issue with solid characters 'n stuff I bet. In the selection, when picking a champions, some mini Icons aren't shown in the top left corner
Something that just happened: I am not able to skill an ability sometimes after leveling up. Does not happen often though.
oh also: wards dont do shit either lol
as well as the portback. It's buggy too. feels like you gotta wait a year until you can backport again after cancelling

Chat messages By Jens#2988 and みつる#4098

**Comment by lzardy** [comment]
Consider splitting this into individual issues. Most of these have been fixed so I will mark it as closed.
