### ISSUE TITLE
 Missile and skill misleading coefficients

### ISSUE THREAD

**Issue by Diego4458** [LeagueSandbox/GameServer#1257]
The EzrealMysticShotMissile has different coefficients than the EzrealMysticShot having its coefficient 0.1 higher than the normal shot and the coefficient 2 being 0 causing the champion to have 0 ap damage in the ultimate and 10% more ad damage.

![Screenshot_4](https://user-images.githubusercontent.com/40145391/148707635-7ac26f66-665f-43c9-bc7d-4416e9a4b8d5.png)
![Screenshot_5](https://user-images.githubusercontent.com/40145391/148707637-a2d428f9-90c9-4cd9-8b3a-98825937923f.png)

the same values ​​are being used in the skills script in the repository

other skills probably suffer from the same problem.

**Comment by lzardy** [comment]
This is an issue of the script rather than the data. The data is correct.

**Comment by Diego4458** [comment]
OK. thanks
