### ISSUE TITLE
Particles wont render if created out of vision

### ISSUE THREAD

**Issue by cabeca1143** [LeagueSandbox/GameServer#1306]
Since #1296, minions such as TT's, Crystal Scar's or Aram's heal relics, won't have their particles rendered at all if they were created out of vision.
They will work normally if you had vision of them when created.

**Comment by Killfrra** [comment]
As I understand it, earlier particles were created immediately for everyone who could see them, if the fog of war did not interfere. Probably due to #1325 and the fact that earlier the object was created first, and only then the visibility was updated, and not vice versa.
