### ISSUE TITLE
Skillshots spawn is wrong in some places of the map

### ISSUE THREAD

**Issue by DeudlyYT** [LeagueSandbox/GameServer#134]
Skillshots spawn is wrong in some places of the map (for example in the middle line)

**Comment by FurkanS1821** [comment]
Also, you can move during cast time and 2 projectiles spawn. One from cast place, one from moved place. Only the one fired from moved place damages.

**Comment by joaquin95** [comment]
Fixed in db88df70353cc1f07c0f5fbfe8e1af5f676791bb
