### ISSUE TITLE
Buff HUD Icons do not show up when playing in the Ascension gamemode

### ISSUE THREAD

**Issue by cabeca1143** [LeagueSandbox/GameServer#1386]
Absolutely no buff or item active effect icons.
Issue seems to be limited to Ascension.
Reason unknown

**Comment by lzardy** [comment]
May have to do with Event networking.

**Comment by cabeca1143** [comment]
Issue is client-side.
If you wish to solve this issue, do the following:

1 - Go to `RADS\solutions\lol_game_client_sln\releases\0.0.1.68\deploy\DATA\menu\hud`
2 - Open `ShurimaElementsListNormal.ini`
3 - Add, at the very botton of the file, the following lines:

```
CenterHUD_ActiveItems.ini
CenterHUD_BuffGroupTracker.ini
TargetBuffGroupNegative.ini
TargetBuffGroupPositive.ini
LeftBuffGroupNegative.ini
LeftBuffGroupPositive.ini
ChampionLeft_Inventory.ini
```
