### ISSUE TITLE
There's something wrong with dash now

### ISSUE THREAD

**Issue by z2481520838** [LeagueSandbox/GameServer#1442]
--It should be the loss of data packets that caused the abnormal display of Dash animation
--There are no problems with Dash's basic functions

**Comment by Killfrra** [comment]
Could you record a video, what does it look like, and how to reproduce it?

**Comment by z2481520838** [comment]
> 你能录制一段视频吗，它是什么样子的，以及如何重现它？

You Can try Akali R

**Comment by z2481520838** [comment]
> Could you record a video, what does it look like, and how to reproduce it?

https://youtu.be/7p1Hu3zos5E

**Comment by z2481520838** [comment]
> Could you record a video, what does it look like, and how to reproduce it?

It's definitely not a problem with the script
I fully guarantee that I am using the "ForceMovement" command
