### ISSUE TITLE
Minions path problems (a lot)

### ISSUE THREAD

**Issue by Deudly** [LeagueSandbox/GameServer#148]
- [x]  Minions accumulate in places (all of them go to the same place)
- [x]  When destroying inhibitors they stop there and they dont do nothing
- [x] They sometimes stop moving. 

Probably there are more bugs to discover with minions

**Comment by hesa2020** [comment]
- Minions accumulate in places (all of them go to the same place)
Should be fixed from my pull request.

**Comment by ICsleep** [comment]
Test 21.11.2018 indev version from 19.11.2018:
I testet around with minions :

- [x]  They sometimes stop moving.

i think i fixt this with my pull request "Fix Minion Movment #774"

- [x] When destroying inhibitors they stop there and they do nothing

I was unable to test that. 

Furthermore : 

-Minions do some buggy movement after finding a target. 

-It may also happen that they walk to far away from their path while following their target.
 They walk trough walls on their way to the next way-point. Reason is (#65)

**Comment by danil179** [comment]
#65 is an old issue, there were already implementations of new algos (it still A* but it uses sort of lib of cylinders, didnt fully understood, see PR about that).

Probably server sends wrong paths (from what I remember it uses tge navmesh, need to check that).

**Comment by lzardy** [comment]
All checks are complete for this particular issue.
