### ISSUE TITLE
Champion stats | Load them from json and not from rads

### ISSUE THREAD

**Issue by DeudlyYT** [LeagueSandbox/GameServer#189]
The champion stats have to be loaded from json files and not from the lol RADS folder. 

Check Champion.cs line 36 for more info

**Comment by Querijn** [comment]
I would make the behaviour so that it would try to find the JSON value for a stat first, and then default to the RAF file's stat if not overridden.

**Comment by Maufeat** [comment]
Done by @FurkanS1821 

And @Querijn that wouldn't be a problem, but we want to get rid of the rads since the Garena Version for example doesn't have RAFs and we want everything to be customizable.
