### ISSUE TITLE
Units with 0% crit chance can crit

### ISSUE THREAD

**Issue by FurkanS1821** [LeagueSandbox/GameServer#195]
This can be fixed by making:
(Unit.cs line 197)
`nextAutoIsCrit = new Random().Next(0, 100) <= stats.CriticalChance.Total * 100;` to:
`nextAutoIsCrit = new Random().Next(0, 100) < stats.CriticalChance.Total * 100;`

Since big changes are expected this night and im busy with another stuff, I wrote it here.

**Comment by joaquin95** [comment]
Fixed in aa01ef7977db1bad43a44f92c37bbcdde6d3b70d
