### ISSUE TITLE
StacksOverflowException

### ISSUE THREAD

**Issue by thchang99** [LeagueSandbox/GameServer#205]
I am a very new developer I might have messed up a step here and there however I synced everything however every single time I launch the server I get the StacksOverflowException which terminates the server and I am not much of a debugger... I would appreciate any help fixing this.. Thank you. #

**Comment by chutch1122** [comment]
Have you made any changes to the project?

**Comment by thchang99** [comment]
Nope

**Comment by thchang99** [comment]
It look like this
![stackoverflow](https://cloud.githubusercontent.com/assets/21373106/18373016/a347446e-760e-11e6-8f59-081bd16a2474.PNG)

**Comment by thchang99** [comment]
@chutch1122

**Comment by Ness199X** [comment]
This was fixed in #199 are you on the latest commit?

**Comment by MythicManiac** [comment]
You can comment that line off if you want to run the server. It would mean you don't get log output to a file anymore, but that shouldn't be a huge issue.

**Comment by Maufeat** [comment]
This issue is because it doesn't create a "Logs" Folder anymore. Not sure why, but to fix that just create a new folder in the binary folder.

**Comment by thchang99** [comment]
Thank you @MythicManiac and @Maufeat!
but even if I put a folder called Logs in the bin folder it showed the Exception again... And I tried //ing the code but it keeps having debugging problems.. (I'm such a nub)

**Comment by thchang99** [comment]
Wait um i kinda figured it out but now I have problems with RAF file directories on my 4.20
My path is right but it keeps saying no path..

**Comment by MythicManiac** [comment]
@thchang99 Try hopping on our discord server from the readme and ask help there, you'll probably get answers faster that way. Anyway, we'd need the full error to know what's up.

**Comment by thchang99** [comment]
Um wait thank you everyone who had replied to my request.. I //ed out the logs part and well I thought /path/to was part of the path to the RAF so that's the part that I screwed up I think.. I really liked the offline sandbox however was somewhat disappointed that other champs where.. well... half the skills did not work and Ahri did not have her orb. 
Um so I think sandbox is really great, but I think that things can get better. I would really like to contribute to the part that is really not that hard kind of coding but that is kind of time consuming.. However I really don't know the basis so  I would need help.. 
So here's a list of things that I think needs improvement (not criticizing.. I think I know what it takes to create even something similar to this..)
1. Reset skill points when changed champions
2. Item buying and using
3. Less crashes (maybe my computer is just bad)
4. Borrowing partial RAF from "new" League..
5 ETC. that needs improvement
Thanks all @chutch1122 @MythicManiac @Maufeat for responding to my request.. 
Peace

**Comment by MythicManiac** [comment]
This project is still very much WIP and currently we don't have a "release" at all, so there are many things missing and needing improvement. Most of the development related conversations are in our Discord (linked in the project readme), so if you're interested in helping out, you should hop in there.

**Comment by Maufeat** [comment]
```
1. Reset skill points when changed champions
2. Item buying and using
3. Less crashes (maybe my computer is just bad)
4. Borrowing partial RAF from "new" League..
5 ETC. that needs improvement
```
1. Since that is just a developer command, no need to spent time on that. Just Level up with `.xp xxxx` and skill again. (not working when spell is maxed)
2. Why? What isnt working? If you refer to stack items, yes that is currently buggy should be fixed soon and easy.
3. I have zero crashes when using the server. Except currently as above mentioned when buying items that has child items.
4. We are sticking with 4.20, there are alot of issues that the new files cause and are may not compatible with 4.20. (Maps, new Champions, etc.)
5. Sure, but I have high expectations, if it continues like that I think we can reach a playable state early next year.

**Comment by thchang99** [comment]
Um @maufeat here are some crashes that I've been getting.. 
When I misspell a champion name or the champion is not in the directory it crashes straightaway...  hope that fixes soon
Yes the items with child items doesn'the work.. it crashes
One thing I forgot to mention on my comment above is that I hope one by one the other Champs then Ezreal can start working.. Ahri doesn'the have her Orb and most of the champions does'that have any skill thingies. Also what's up with Riven... it's not even in the content at all.. 
Yes hopefully it gets all fixed by the end of the year... I know this project had been resurrected from intwars  and it's getting better everyday.

**Comment by dertrutinator** [comment]
I have that error as well, but I don't know anything about programming, so could you tell me exactly how to "comment the part off" ?

**Comment by thchang99** [comment]
Okay @detrutinator. Quoting a  means that it makes the compiler (in this case) slip skip the coding so such unneed things that cause errors can be skipped.. so basically you see my picture above, right? Put two slashes // in front of each coding that have words. So double slash those three lines. I'm doing this on my phone so I don't exactly know but I think there's one more line in that section that says stuff about logs so slash that one out too.. if there isn't... well I'm stupid.. so the way you get to the logger is that when you build it and f5 it it's gonna show you debug stuff and so on. Do what I told you to those codes and rebuild solution and f5 It again. If you got your path right, it should work fine. 
Peace

**Comment by dertrutinator** [comment]
@thchang99 like this?
`//File.AppendAllText(
                        //Path.Combine(_executingDirectory, "Logs", _logFileName),
                        //text + Environment.NewLine`

**Comment by thchang99** [comment]
@dertrutinator yes

**Comment by MythicManiac** [comment]
This has been fixed now
