### ISSUE TITLE
Compiling seems to delete LeagueSandboxGameServer.exe

### ISSUE THREAD

**Issue by dertrutinator** [LeagueSandbox/GameServer#211]
When trying to fix #205 by typing // in front of the critical lines, compiling these changes seems to delete previous versions of LeagueSandboxGameServer.exe, but not creating a new one, which causes the compiling process to fail. This also occurs when the project was never compiled before. I am pretty sure I followed the instructions correctly though. What can I do about this?

**Comment by Maufeat** [comment]
I am sure this is stuff you should know. I will close this one, try to start with some basics or wait for a release.
