### ISSUE TITLE
CS0006

### ISSUE THREAD

**Issue by thchang99** [LeagueSandbox/GameServer#220]
I believe this thing had been bothering a lot of people including me.. Metadata file error and stuff. It says it can find the Metadata file form the Exe file for sandbox. I think it might be a Visual studio problem..

**Comment by MythicManiac** [comment]
This description of the problem doesn't really tell much. A full error would be more useful.

**Comment by thchang99** [comment]
Wait.. Figured it out 
 // File.AppendAllText(
                     // Path.Combine(_executingDirectory, "Logs", _logFileName),
                     // text + Environment.NewLine
                   // );
                   //Console.WriteLine(text);
It used to work when I didn't slash out the  ); for some reason..

**Comment by thchang99** [comment]
Sorry for making an issue.. Please close this..
