### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by thchang99** [LeagueSandbox/GameServer#226]
var playerConfigurations = data.SelectToken("players");
            foreach (var player in playerConfigurations)
            {
                var playerConfig = new PlayerConfig(player);
                Players.Add(string.Format("player{0}", Players.Count + 1), playerConfig);
            }

            //Read cost/cd info
            var spellInfo = data.SelectToken("spellInfo");
            CooldownsDisabled = (bool)spellInfo.SelectToken("NO_COOLDOWN");
            ManaCostsDisabled = (bool)spellInfo.SelectToken("NO_MANACOST");

            In Config.cs it says "Object reference not set to an instance of an object."
             Works fine without without it if I quote it(I actually like the cooldowns and mana/energy. Thank you), but I guess sometimes URF is fine.. 

Also um I really like the reloadlua update.. I believe you are working on the champions so may the force be with you with that.. You (as in plural in respect of everyone contributing) are really doing a great job on this project so let's keep this rolling! This have already gotten so much better when I got it from like three weeks ago. Thank you so much.
Peace-

**Comment by Maufeat** [comment]
Shouldn't hard to fix by your self. Delete your GameMode.json in Settings and use the new template from Furkan.
