### ISSUE TITLE
Sometimes tier 3 towers dont spawn

### ISSUE THREAD

**Issue by DeudlyYT** [LeagueSandbox/GameServer#231]
Sometimes for strange reasons, one or more tier 3 towers dont spawn.
- [ ] Sometimes tier 3 tower dont spawn

**Comment by FurkanS1821** [comment]
You mean inhibitor towers? I never saw this (exceptiong blue bot inhibitor tower)

**Comment by DeudlyYT** [comment]
@FurkanS1821 Yes, I mean inhibitor blue bot tower

**Comment by Maufeat** [comment]
Should have been fixed already. Problem was/is that the name of that Turret wasn't correct.
