### ISSUE TITLE
Targeted projectiles (including AA) doesn't deal damage 75% of the time

### ISSUE THREAD

**Issue by FurkanS1821** [LeagueSandbox/GameServer#232]
- [x] Find out which commit caused the bug

Found, 

- [x] Find out which code change caused the bug

Found.

- [X] Fix the code

Fixed

- [X] PR the code

Done.

**Comment by FurkanS1821** [comment]
Because `GameObject.Collide()` doesn't return true each time.

**Comment by TheWebs** [comment]
I assume that turret shots are included in this case because they dont always do damage when they're supposed to.

**Comment by DeudlyYT** [comment]
@FurkanS1821 Close this
