### ISSUE TITLE
Minions ignore turrets

### ISSUE THREAD

**Issue by FurkanS1821** [LeagueSandbox/GameServer#233]
- [X] Fix AA bug, whoever caused it

Done.

- [X] Find the commit caused the bug

That's me xD ([commit](https://github.com/LeagueSandbox/GameServer/commit/877881acdc0e9817faf672ef17aac17b70787058))

- [X] Find the code caused the bug

Done.

- [X] Fix it

Done.

- [X] PR it

Done.

**Comment by DeudlyYT** [comment]
What? Is this a new bug? @FurkanS1821

**Comment by FurkanS1821** [comment]
I have been trying to get what the fuck caused the bug, do you remember when it worked? @DeudlyYT
