### ISSUE TITLE
Make old 3v3 map avariable alongside the other maps

### ISSUE THREAD

**Issue by axydavid** [LeagueSandbox/GameServer#243]
Is it possible to bring the old 3v3 map back to 4.20?
What roadblocks are there to prevent this?

**Comment by MythicManiac** [comment]
We have custom maps on our roadmap, so it is going to be possible whenever that's implemented. I'm unsure what it would require right now, but if porting isn't an option, you could just re-create it yourself.

**Comment by FurkanS1821** [comment]
File system had changed in 4.17, so only thing we can do is to port it to new system. I want that map so much too but it seems hard.

**Comment by axydavid** [comment]
hmm well, so basically it should be possible longer down the road
