### ISSUE TITLE
Add OSX compatibility to ENetSharpLeague

### ISSUE THREAD

**Issue by MythicManiac** [LeagueSandbox/GameServer#265]
Should be done eventually

**Comment by DeudlyYT** [comment]
As @molenzwiebel said. He has a working ENet# working. Tell him

**Comment by MythicManiac** [comment]
@DeudlyYT it requires more than just having a working compiled version of ENet. You'll need to turn the ENetCS into a generic non-platform specific library. Currently it's only working for Windows.
