### ISSUE TITLE
Add Linux support to ENetSharpLeague

### ISSUE THREAD

**Issue by MythicManiac** [LeagueSandbox/GameServer#266]
This might or might not be tricky, but should be done soon

**Comment by Deudly** [comment]
Already done

**Comment by MythicManiac** [comment]
Not done yet as the one that's in our requirements doesn't work on linux. Re-opening

**Comment by MythicManiac** [comment]
Considered done once the NuGet package in our repository works on Linux. Feel free to contact me about updating the package if a version exists where it works on Linux as well.
