### ISSUE TITLE
League of Legends caused ACCESS_VIOLATION in module League of Legends

### ISSUE THREAD

**Issue by testanull** [LeagueSandbox/GameServer#271]
Hello,
I got this problem when start game
"League of Legends caused ACCESS_VIOLATION in module League of Legends"
How can i fix this?

**Comment by MythicManiac** [comment]
This sounds like an issue with your League of Legends installation, and not the sandbox. I'm closing this issue from github, but you can visit our Discord and seek help from there.

Link to Discord: https://discord.gg/0vmmZ6VAwXB05gB6
