### ISSUE TITLE
Changes needed to allow the Public Testing Environment to spawn multiple GameServer instances

### ISSUE THREAD

**Issue by MatthewFrench** [LeagueSandbox/GameServer#281]
2 changes are needed for the main fork to be usable in the testing environment:
(1) --config-json argument needs added to allow passing a direct string of JSON into GameServer.
(2) A "Game is ready." log line needs added to tell the testing environment when the GameServer is ready to accept players.

**Comment by JoaRiski** [comment]
Could this be clarified a bit? Issues should be formatted in a way that technically anyone could solve them with the specs in the issue.

From the current description, I see we need a way to input the configuration as a string to the app, but beyond that I'm not sure what does it mean

**Comment by MythicManiac** [comment]
Could this be clarified a bit? Issues should be formatted in a way that technically anyone could solve them with the specs in the issue.

From the current description, I see we need a way to input the configuration as a string to the app, but beyond that I'm not sure what does it mean
