### ISSUE TITLE
Create a Discord bot for creating issues on github

### ISSUE THREAD

**Issue by MythicManiac** [LeagueSandbox/GameServer#289]
It would be very convenient to be able to create issues in Discord by typing something like

`!issue "Some issue" "Some description"`

**Comment by MythicManiac** [comment]
This has been completed, bot source at https://github.com/LeagueSandbox/IssueBot

Bot is now running on the Discord server, accepting input on any other channel besides #public
Command syntax is `!issue [repository] [title] [description]`

**Comment by kberg** [comment]
Hi -- I'm curious how this has been working even now six years later. I'm interested in such a feature, and you seem to be the only game in town. :D

**Comment by MythicManiac** [comment]
Check the https://github.com/LeagueSandbox/IssueBot repo, it's not really up to date and I doubt you can even build it, but if you're fine running Docker you can use it from here: https://hub.docker.com/r/leaguesandbox/issuebot
