### ISSUE TITLE
Reconnecting is not working

### ISSUE THREAD

**Issue by MythicManiac** [LeagueSandbox/GameServer#41]
The server never marks a player as disconnected even when the disconnect message is received. It also prevents a new connection to a player's ID if the player is already connected. This results in reconnecting being impossible.

**Comment by MythicManiac** [comment]
Looks like I won't have the time to do this just  yet afterall

**Comment by coquicox** [comment]
Don't worry, we got time

**Comment by coquicox** [comment]
I give fastly a look, it's pretty easy. You have to send every creeps and champs like in HandleSpawn
