### ISSUE TITLE
cancel aa when disarmed during a

### ISSUE THREAD

**Issue by Deudly** [LeagueSandbox/GameServer#459]

**Comment by MythicManiac** [comment]
More verbose details please

**Comment by Deudly** [comment]
At this moment, when you get disarmed, if you are auto attacking the attack WON'T stop. 

In League, if someone applies disarm to anybody that is attacking his AA stops

**Comment by lzardy** [comment]
Fixed, close this issue. The Debuff Disarm calls StopMovement, which then calls NotifyInstantStopAttack, which then stops any active auto attacks.
