### ISSUE TITLE
Fix formating issues

### ISSUE THREAD

**Issue by moonshadow565** [LeagueSandbox/GameServer#491]
Big number of methods don't follow formating guidelines.
Example:
```
        public virtual void update(float diff)
        {
            Move(diff);
        }
```

**Comment by hemirime** [comment]
I guess #571 and https://github.com/LeagueSandbox/LeagueSandbox-Default/pull/62 already fixed this issue. Am I right?

**Comment by FurkanS1821** [comment]
They should have but we might have missed something.

**Comment by danil179** [comment]
Could be done easily by automatic script (or already existing tool). Close this currently, reopen and comment if needed.
