### ISSUE TITLE
Untargettability 

### ISSUE THREAD

**Issue by Deudly** [LeagueSandbox/GameServer#493]
> Untargettability is not implemented but should be. Probably as a buff
> -Mythic

**Comment by moonshadow565** [comment]
Related to #492 
TL;DR it should be stat

**Comment by superewald** [comment]
**close request**: resolved by #987 ?

**Comment by danil179** [comment]
> 
> 
> **close request**: resolved by #987 ?

This not about building, but about units if I'm not mistaken. This is API changes.

**Comment by superewald** [comment]
> > **close request**: resolved by #987 ?
> 
> This not about building, but about units if I'm not mistaken. This is API changes.

You're right, I will include this in my buff mini-rework.

**Comment by Kubeer** [comment]
Technically SetIsTargetableToTeam is working but the health bar is not transparent.
