### ISSUE TITLE
NavGrid:GetCell - Ranged abilities can exceed length of Cells array at certain locations, causing crashes

### ISSUE THREAD

**Issue by indiemini** [LeagueSandbox/GameServer#521]
Using ranged abilities (including flash, Ezreal E, etc) aimed past the northern wall on the 4.20 SR causes crashes.
![screen05](https://user-images.githubusercontent.com/6320771/32420596-b20f9444-c25a-11e7-97a9-34e6e2525eff.png)

Cells.Length: 86142
Attempted to grab at index: 86382

GetCell is called and attempts to fetch Cells[86185] (and often higher) when the array only has 86142 elements, thus causing an index out of bounds exception. We can simply ignore this and log to console when it happens (which is how I was debugging it) but that could have unintended side effects...

I have not tested this on other maps.

**Comment by MythicManiac** [comment]
Well described issue, nice work :+1:
