### ISSUE TITLE
Loading Screen Player Info

### ISSUE THREAD

**Issue by Skinz3** [LeagueSandbox/GameServer#559]
There is a problem in the loading screen, when two people are connected, they are respectively not connected, problem of PKT_S2C_LoadPing?

**Comment by Skinz3** [comment]
[](url)https://ibb.co/iO1z5o

**Comment by Maufeat** [comment]
Missing packet in LoadScreen Channel - We might have some infos about that on our discord. (#development channel)

**Comment by Skinz3** [comment]
Thanks :) Im trying to make my own emulator in order to get this  https://github.com/Skinz3/Legends here is my discord : Skinz#1128
