### ISSUE TITLE
Show damage text to only the damage dealer and the damaged

### ISSUE THREAD

**Issue by FurkanS1821** [LeagueSandbox/GameServer#569]
As that's the case with normal league.

**Comment by MythicManiac** [comment]
Sounds like something that could be made configurable

**Comment by HarmfulBreeze** [comment]
If you want to properly emulate League's behavior, you shouldn't make it configurable IMO (or only for debug purposes).
Just imagine the insane amount of damage text you'd see in an actual game 🤔

**Comment by JoaRiski** [comment]
We don't want to emulate league, we're a sandbox 😄

**Comment by MythicManiac** [comment]
We don't want to emulate league precisely, we're a sandbox 😄
