### ISSUE TITLE
API for client events

### ISSUE THREAD

**Issue by danil179** [LeagueSandbox/GameServer#682]
Add API for client events, all the requests from the client should invoke events like:
```
OnSpawn
```
or 
```
OnBlueTip
```

that way it is easier to create scripts by listen to these events.

**Comment by MythicManiac** [comment]
Extra specs required for what events should we add and when should they be triggered

**Comment by danil179** [comment]
All the events that client invokes (clicks, attacks, spell cast, emotes, chat messages etc) that the server should know about, for start it's all the packets as events.

this should be incrementally done as we progress.

I already done that in my PR so this issue is about the problem that currently no event API exist.

**Comment by MythicManiac** [comment]
Ah, didn't notice there was a PR for this already, that should be sufficient 👍

**Comment by danil179** [comment]
Close this issue in favor of #696.
