### ISSUE TITLE
Update WIKI

### ISSUE THREAD

**Issue by hesa2020** [LeagueSandbox/GameServer#694]
The wiki commands are outdated.

https://github.com/LeagueSandbox/GameServer/wiki

See "Commands" menu.

**Comment by FurkanS1821** [comment]
How is it outdated? I updated them 3 days ago, right after command char was switched to `!` from `.`, that page was empty before that.

**Comment by hesa2020** [comment]
Maybe i didnt had latest build then, because my build was still using the `.` and didnt had

`!kill <minionsblue|minionspurple>`

**Comment by danil179** [comment]
https://github.com/LeagueSandbox/GameServer/wiki/4.09.-Commands is updated. Issue fixed & closed.
