### ISSUE TITLE
Proposal to make proper use of GitHub's issue labels

### ISSUE THREAD

**Issue by Veykril** [LeagueSandbox/GameServer#703]
This Issue proposes a specific issue label layout to use to make issue's easier to identify. Issues will be categorized in specific `tag groups` which makes up the first letter of the label followed by a short-hand descriptive word or phrase. These will be color coded according to their tag group. The following table list's the currently planned tags and their associated groups:

| *TAGS LABELS*            |               Meaning                             |
|:-------------------------|:--------------------------------------------------|
| *AREA TAGS*              | What part of the code is relevant?                |
| A-content-pipeline       | Content loading related                           |
| A-packets                      | Packet related                                                 |
| A-script-engine                      | Script engine related                                   |
| A-?                      | //todo: add other Areas                                   |
| &nbsp;                                                                       |
| *BLOCKER TAGS*           | Issue is blocking on something before it can be resolved |
| B-reproduce              | Blocked on a need to reproduce problem locally    |
| B-needs-verification     | Blocked due to missing verification               |
| &nbsp;                                                                       |
| *EFFORT TAGS*            | The expected complexity of fixing the issue       |
| E-easy                   | Effort: easy                                      |
| E-good-first-issue                   | Effort: Issue which will help you get into the project |
| E-help-wanted            | Assignee/Issue creator requests help?             |
| &nbsp;                                                                       |
| *IMPACT TAGS*            | The effect of the issue remaining unresolved.     |
| I-cleanup                | No impact; the issue is one of maintainability or tidiness. |
| I-crash                  | Application crash                                 |
| I-enhancement            | No impact; the issue is a missing or proposed feature. |
| I-performance            | Unnecessary memory usage/Performance degradation  |
| I-wrong                  | An incorrect behaviour is observed(bug).          |
| &nbsp;                                                                       |
| *PRIORITY TAGS*          |                                                   |
| P-high                   | Priority: High                                    |
| hacktoberfest            | Priority: Hacktoberfest, no prefix cause it's a special github label iirc |
| &nbsp;                                                                       |
| *STATUS TAGS*            |                                                   |
| S-clarifying             | This issue needs clarification                    |
| S-has-open-pr            | There is a PR open that resolves the issue        |
| S-testing-needed         | Needs testing                                     |
| S-verified               | This issue has been verified                      |
| S-wont-fix               | The issue will not be fixed                       |
| &nbsp;                                                                       |
| *TEAM TAGS*              |                                                   |
| T-?                      | for when we might have teams that are to be associated with specific areas? |

This issue is meant as a discussion for thoughts and ideas to add to this.

**Comment by MythicManiac** [comment]
Sounds like something we can try out to me, but I'd like to hear at least a couple of other people's opinions

**Comment by MythicManiac** [comment]
Vote to the issue with 👍 and 👎. This will be put into effect sometime next weekend if there are more votes for than against.

**Comment by moonshadow565** [comment]
need more priority tags

**Comment by MythicManiac** [comment]
I disagree, because people ignore priority and just work on whatever they want to anyway. It's enough that we can make some issues stand out as high priority

**Comment by MythicManiac** [comment]
Looks like we can put this into action
