### ISSUE TITLE
Update to the new SR

### ISSUE THREAD

**Issue by Neekhaulas** [LeagueSandbox/GameServer#71]

**Comment by Redditus** [comment]
has there been any work on it yet? I tried this python script: 
[url=https://www.dropbox.com/s/remcrdk7fcxvg4x/lolmap%20parse.zip]https://www.dropbox.com/s/remcrdk7fcxvg ... 0parse.zip[/url]

Well, it works with let's say new SRU 4.20, but not with a newer Version of the Rift (e.g. 6.10 aimesh_ngrid)

Or is there any other method currently to use to get a proper use of the updated map?

**Comment by coquicox** [comment]
What is this script purpose?

**Comment by Redditus** [comment]
https://www.reddit.com/r/leagueoflegends/comments/298pt7/help_pls/

aimesh_ngrid to bmp

**Comment by coquicox** [comment]
Actually what I say with update to the new SR is put the rights level props for the level but what you're giving is for the pathfinding and could be usefull

**Comment by Redditus** [comment]
Because currently it is really unresponsive on the new Rift. When casting a spell for ex. you teleport a bit left down. Is that because of the Pathfinding? If so, I hope you all can get the aimesh_ngrid to work for with the project

**Comment by coquicox** [comment]
Pathfinding is actually fully calculated on the client. On the real LoL, client process the movement and server validate it or send a new one

**Comment by FurkanS1821** [comment]
How can I use this aimesh_ngrid to bmp tool?

**Comment by MythicManiac** [comment]
Closing this for now as the new SR is in the project, might just not work perfectly yet. Further issues should be opened as bugs.
