### ISSUE TITLE
Use Vector2 on the ITarget interface for coordinates

### ISSUE THREAD

**Issue by MythicManiac** [LeagueSandbox/GameServer#721]
Currently the `ITarget` interface has two ways of getting coordinates, those being:
- The `X` and `Y` float properties
-  The `GetPosition()` method that returns a Vector2

Replace both of these with a `Vector2 Position` property

Source: https://github.com/LeagueSandbox/GameServer/pull/719/files/eb186990a214b6012aa31b0956c6cafaafcf2fd3#diff-cc5aeb1d18845b208bc1b1bfd0ce90ef

**Comment by rexiaxm7** [comment]
Hello. May I do it?

**Comment by Veykril** [comment]
This already seems to have an open PR(#721) that implements this

**Comment by danil179** [comment]
The #735 PR is full of conflicts because it wasn't merged on time. Solving the conflicts is also progress for this PR.
