### ISSUE TITLE
Custom champion creation support

### ISSUE THREAD

**Issue by MythicManiac** [LeagueSandbox/GameServer#73]
Support for creating new champions from scratch

**Comment by DeudlyYT** [comment]
@MythicManiac Now Custom Champion Creation is supported! Just check https://github.com/DeudlyYT/Tree

Maybe you should close this issue

**Comment by MythicManiac** [comment]
It isn't supported in the way we'd want to yet. Primarily custom content loading is working, but creation is still a whole load of tinkering
