### ISSUE TITLE
Disable skill cast while there is another being casted

### ISSUE THREAD

**Issue by viniciuslrangel** [LeagueSandbox/GameServer#758]
e.g. Ezreal use R and E at the same time
Except summoner spells

**Comment by moonshadow565** [comment]
Can someone verify this?
I'm not sure that's how this works.
What i assume is happening is: SpellCast > Disable All Spells Except sums > Delay until hidden projectile hits > Hidden SpellCast > Actual projectile hits

**Comment by viniciuslrangel** [comment]
Need to check the situation of some cancellable skills (Katarina's R)

**Comment by lzardy** [comment]
In that case, it is not due to code preventing it, but lack of code for replacing abilities. (Ex: Katarina r replaced by cancel r, they are 2 separate spells).

**Comment by viniciuslrangel** [comment]
But you can cancel by pressing other skills, I guess this commit would prevent that from happening. I will check soon.

**Comment by lzardy** [comment]
So wait, is this about cancelling or doing two at the same time, since the OP suggests you’re using E and R at the same time.

**Comment by viniciuslrangel** [comment]
Two at the same time. My bad, this comment was most like to be just a new issue
