### ISSUE TITLE
Turret destroyed announcement

### ISSUE THREAD

**Issue by coquicox** [LeagueSandbox/GameServer#80]
And gold for the team

**Comment by Devile** [comment]
Should work now. https://github.com/LeagueSandbox/GameServer/commit/9fcebbd954680d332759d79f41e0a1c4555ae68c

Could someone remove the empty commit, please?

**Comment by MythicManiac** [comment]
@Devile did you create a new branch/pr for it yet?

**Comment by Maufeat** [comment]
#112 should be alright now
