### ISSUE TITLE
Fix projectiles only spawning on owner position

### ISSUE THREAD

**Issue by lzardy** [LeagueSandbox/GameServer#818]
Currently we only have AddProjectile and AddProjectileTarget functions, both of which only spawn on owner position. This makes it hard/impossible to make scripts that spawn client projectiles at cast position. Ex: Nidalee Q spawns client projectile at cast position, meaning normally you can't press Q and flash and it hit sooner than if you stayed in the same spot. Currently you can Q then flash and it will hit sooner than normal. **TLDR:** Make AddProjectileCoords function which uses fromX and fromY as parameters instead of hard coded Owner.X and Owner.Y.

**Comment by danil179** [comment]
It's not that all projectiles cast in cast position?
