### ISSUE TITLE
Dash code Problem

### ISSUE THREAD

**Issue by xxx3456789** [LeagueSandbox/GameServer#822]
When you use DashToLocation or DashToTarget
the animation was Dashing, but actually it was walking to there, and speed(dash) was for animation, actual spot like i said, it was walking to target (you can see the problem when you CancelDash earlier)
so It need to fix:
1. Dash to target should not be walking to there
2. If it can't fix, then use Walking Speed = Dash Speed, when it reach last position, CancelDash.

**Comment by lzardy** [comment]
DashToTarget is not implemented fully: https://github.com/LeagueSandbox/GameServer/blob/aeb35b5d27db66e833097a8217f939405734c092/GameServerLib/GameObjects/AttackableUnits/AI/ObjAIBase.cs

**Comment by danil179** [comment]
The problem is that movespeed is a stat so you can't simply change it (e.g. Some items give ms bonus). You need to know what is the dash bonus to ms.
