### ISSUE TITLE
inhibitor and Nexus can't be damage by Autoattack

### ISSUE THREAD

**Issue by xxx3456789** [LeagueSandbox/GameServer#830]
As Title, we can attack turret but Inhibitor and nexus can't
and it can damaged by AOE spell damage (like Taric's W,R without selecting target, which is deal damage to all target). 
does it affact from Attack Range or something?

**Comment by lzardy** [comment]
Inhibitors and Nexus are untargetable due to vision being blocked by the map’s buildings

**Comment by danil179** [comment]
Related/Duplicate #580 #724
