### ISSUE TITLE
Fix pathing through buildings

### ISSUE THREAD

**Issue by danil179** [LeagueSandbox/GameServer#843]
Currently, `IsWalkable` and `IsAnythingBetween` check only the NON_PASSABLE flag. We need to add the SEE_THROUGH = 0x40 flag to the check also, and treat it like NON_PASSABLE.

Related #580, #299, #148

**Comment by DannyDelic** [comment]
Unsure what the SEE_THROUGH flag actually means, but I am going to add the check.

**Comment by wildbook** [comment]
As far as I know some things are see-through but not passable. For example I imagine inhibitors/nexus and similar are.

Thanks in advance for the contribution :)

**Comment by lzardy** [comment]
#848 Already fixes this, it just needs to be implemented. #838 accounts for vision through these buildings (as long as they are SEE_THROUGH).

**Comment by DannyDelic** [comment]
Okay, is there any way I can tell if someone is doing a certain issue, as to avoid duplicating work/code.

**Comment by lzardy** [comment]
Usually references are made in PRs (a reference was made above), other than that, check the currently available PRs to know what issues might fall into their reach.
Easiest way may be to just ask on the dev. discord.

**Comment by DannyDelic** [comment]
I am not a dev on discord yet, did ask an admin to assign me a role.
