### ISSUE TITLE
Discussion location buff/champion scripts

### ISSUE THREAD

**Issue by abosma** [LeagueSandbox/GameServer#849]
Currently frequently changed Champion and Buff scripts are in the same submodule as the generated content that's almost never changed. With the new content loading refactor it seems better for scripts and content to be split from eachother and maybe make another submodule for LeagueSandbox-Scripts with LeagueSandbox-Default having a dependency on that folder.

**Comment by lzardy** [comment]
What issue does giving the Default a dependency solve? Or rather, what benefit does it give?

**Comment by abosma** [comment]
It's mostly for the amount of updating the champion and buff scripts have compared to the rest of the content. By separating the content and creating a dependency between default and scripts we won't have to update the submodule for LeagueSandbox-Default every time people commit a new champion spell or buff.

If separated we could probably even keep the never updated content (AIMesh, Globals, Items, Maps, Properties, Spells, Talents) in the main directory.

**Comment by danil179** [comment]
Seems like it was resolved in #850.
