### ISSUE TITLE
Add turrets model names

### ISSUE THREAD

**Issue by danil179** [LeagueSandbox/GameServer#867]
Currently we create turrets without model names. The names used for creation are the visual names and so doesn't contain the important info like collision radius and so. `_game.ObjectManager.AddObject(new LaneTurret(_game, "Turret_T1_R_03_A", 10097.62f, 808.73f, TeamId.TEAM_BLUE, TurretType.OUTER_TURRET, GetTurretItems(TurretType.OUTER_TURRET)));`

`Turret_T1_R_03_A` is visual name. `TT_OrderTurret1` is AI/Server name.

**Comment by lzardy** [comment]
The model for the turret named `Turret_T1_R_03` is actually `OrderTurretNormal`.
These models can be found in `League-of-Legends-4-20\RADS\solutions\lol_game_client_sln\releases\0.0.1.68\deploy\LEVELS\Map1\Scripts\CreateLevelProps.luaobj`.
Ideally we would implement all of this *after* a content update which implements reading of additional defaults data such as lua files (human-readable luaobj files).

**Comment by lzardy** [comment]
Resolved by #1219 and subsequent related PRs.
