### ISSUE TITLE
Use .NET Core

### ISSUE THREAD

**Issue by pipe01** [LeagueSandbox/GameServer#871]
This will allow the server to be ran on Linux and MacOS

**Comment by MythicManiac** [comment]
FWIW, this is already linux compatible and should be mac compatible if you use mono. .NET Core isn't a bad idea in itself however.

**Comment by Izumemori** [comment]
Now that .NET Core 3.0 is out there is absolutely no reason to not port it.

**Comment by danil179** [comment]
I think so too

**Comment by danil179** [comment]
#906, #896 related
