### ISSUE TITLE
GameServer\PacketDefinitions420\bin\Debug with nothing inside

### ISSUE THREAD

**Issue by NVThai151097** [LeagueSandbox/GameServer#876]
I apologize if I was too stupid but when I ran the project, it said: PacketDefinitions420.dll is missing
did i do anything wrong?

**Comment by NVThai151097** [comment]
CS0234	The type or namespace name 'Game' does not exist in the namespace 'LeaguePackets' (are you missing an assembly reference?)	PacketDefinitions420	E:\Android\GameServer\PacketDefinitions420\PacketNotifier.cs	14	Active

**Comment by lzardy** [comment]
Please ask these questions in the discord so as to not clutter the issues.
Try the Restore NuGet Packages option that is shown when right clicking the top-most item called "Solution - GameServer" in Visual Studio.

**Comment by NVThai151097** [comment]
thank you.I will close this issue!
