### ISSUE TITLE
Exceptions should be handled in the code

### ISSUE THREAD

**Issue by danil179** [LeagueSandbox/GameServer#912]
In order to avoid random exceptions from throwing into the console, we should remove the exception handling in Server.cs:
https://github.com/LeagueSandbox/GameServer/blob/0b4aa2a0f737d13548b5f5fc1ff8ca5b74697888/GameServerLib/Server.cs#L29

Remove all the lines that throw exceptions to the console.

**Comment by evlnyng** [comment]
I would like to work on this!

**Comment by danil179** [comment]
Seems like it has been done already
