### ISSUE TITLE
I cannot find the file to start the server in the downloaded server file

### ISSUE THREAD

**Issue by Dragondel** [LeagueSandbox/GameServer#931]
Can anyone help me

**Comment by MingSaber976** [comment]
Follow the GUIDE and VIDEO in YouTube, and you will know where's the problems

**Comment by Dragondel** [comment]
Please send me a tutorial link friend------------------ 原始邮件 ------------------
发件人: "MingSaber976"<notifications@github.com>
发送时间: 2019年12月9日(星期一) 中午1:50
收件人: "LeagueSandbox/GameServer"<GameServer@noreply.github.com>;
抄送: "Dragondel"<84434259@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [LeagueSandbox/GameServer] I cannot find the file to start theserver in the downloaded server file (#931)



Follow the GUIDE and VIDEO in YouTube, and you will know where's the problems
 
&mdash;

**Comment by Dragondel** [comment]
> 遵循YouTube中的指南和视频，您会知道问题出在哪里

Please send me a tutorial link friend

**Comment by MingSaber976** [comment]
Follow the GUIDE and VIDEO in ****YouTube**** , and you will know where's the problems
