### ISSUE TITLE
QuadTree map size

### ISSUE THREAD

**Issue by danil179** [LeagueSandbox/GameServer#938]
https://github.com/LeagueSandbox/GameServer/blob/6784b2c87a69614b9c9111eac0e403cfa56169f1/GameServerLib/GameObjects/Other/CollisionHandler.cs#L48

As the QuadTree doesn't work with the real map size which is 14700, 16000 was needed. Figure out why and fix this hardcoded value.

**Comment by lzardy** [comment]
(X, Y) dimensions of the map (determined via navgrid): (14640.673, 14777.2646)

**Comment by Crauzer** [comment]
`As the QuadTree doesn't work with the real map size which is 14700, 16000`

Could you elaborate ?

Collision seems to be working with the values @microsoftv provided.

**Comment by lzardy** [comment]
Be sure to check collisions on all corners of the map given the dimensions of the navgrid. Usually with a lower than needed size, collisions will occur less and less often as units move farther from the origin of the map.

**Comment by Crauzer** [comment]
This could most likely be happening due to faulty usage of the QuadTree or the QuadTree itself being not properly implemented.

How is the quad tree currently being subdivided and what is the max depth ?

**Comment by danil179** [comment]
@Crauzer We use a C# lib for QuadTree (UltimateQuadTree) and I don't think a popular C# lib will be so faulty. I guess the problem is something with the collision radius or some configurations. (U think that max depth default value is 10, but that doesn't really needed for the QuadTree to work, it is just for optimizations)
