### ISSUE TITLE
Remove Target/ITarget Class

### ISSUE THREAD

**Issue by lzardy** [LeagueSandbox/GameServer#955]
Complaints regarding this class include:
1. "It has too many responsibilities."
2. "Target should be its own class without all objects inheriting it."
3. "It couples everything."
4. "In the case of spells, it should be replaced with CastInfo."
Information regarding CastInfo can be found [here](https://github.com/moonshadow565/LeaguePackets/blob/master/LeaguePackets/Game/Common/CastInfo.cs).

**Comment by danil179** [comment]
Resolved in #1036
