### ISSUE TITLE
HandleDisconnect function decoupling

### ISSUE THREAD

**Issue by danil179** [LeagueSandbox/GameServer#986]
Currently the HandleDisconnect is in `Game` class, where it should send events in addition to the champion in order to handle the walking to the fountain, etc..., in the Champion class.

https://github.com/LeagueSandbox/GameServer/tree/indev/GameServerLib/Game.cs#L265

**Comment by danil179** [comment]
Refs #985

**Comment by superewald** [comment]
@danil179 I'm not 100% certain if I understood the task correctly but it does make sense this way :)
