### ISSUE TITLE
crash when casting skillshots

### ISSUE THREAD

**Issue by superewald** [LeagueSandbox/GameServer#988]
The GameServerConsole crashes when casting skillshots since c411d54a87d30f76b0058fa655dae6e0ad864de0.

## Details

When casting a skillshot (Blitz Q, Cait Q/E, Ezra Q/W/R,...) the following exception occurs:
`System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection.'` https://github.com/LeagueSandbox/GameServer/blob/c411d54a87d30f76b0058fa655dae6e0ad864de0/GameServerLib/GameObjects/GameObject.cs#L127

This happens because `Waypoints[]` is empty but `WaypointIndex = 1`.

## Possible Solution

Quick way is to revert c411d54a87d30f76b0058fa655dae6e0ad864de0. This PR has to be checked again.

**Comment by danil179** [comment]
## Hotfix
Change `https://github.com/LeagueSandbox/GameServer/blob/c411d54a87d30f76b0058fa655dae6e0ad864de0/GameServerLib/GameObjects/GameObject.cs#L121` from line 121-128 with `next = new Vector2(Target.X, Target.Y);`
