### ISSUE TITLE
crash when casting gangplank Q

### ISSUE THREAD

**Issue by superewald** [LeagueSandbox/GameServer#989]
The GameServerConsole crashes when casting Gangplank Q.

## Details

When casting Gangplanks Q the following exception gets thrown: 
`System.InvalidOperationException: 'Collection was modified; enumeration operation may not execute`.
https://github.com/LeagueSandbox/GameServer/blob/d089d5f6d148d769b11973eb4a0980f79ce3f7f3/GameServerLib/GameObjects/Other/CollisionHandler.cs#L50

**Comment by danil179** [comment]
The error occurs as _objects change due to Gangplank Q hits an object. While looping in the collision loop we need to remove the projectile, and that will modify the objects in the loop, creating a problem.

Solution #1: Loop over temporary copies of _objects
Solution #2: Lock the loop (but then we will probably end in a deadlock)
Solution #3: Avoid removing objects right away. Always remove the objects at some defined point.

**Comment by superewald** [comment]
As long as I understood you right, you say the actualy cause is this line:
https://github.com/LeagueSandbox/GameServer/blob/c7f31b9c362a55d1901245ea78a15e9ad0aaa69a/Content/LeagueSandbox-Scripts/Champions/Gangplank/Q.cs#L56

But when I just remove it (i would expect to not crash and the projectile stuck at colliding position) the same crash still occurs.

**Comment by danil179** [comment]
Line 27 is the problem. The problem is the collision of the projectile with minions which causes to add some type of particle.

**Comment by superewald** [comment]
Ok I now understand what's going on. 

> The error occurs as _objects change due to Gangplank Q hits an object. While looping in the collision loop we need to remove the projectile, and that will modify the objects in the loop, creating a problem.
> 
> Solution #1: Loop over temporary copies of _objects
> Solution #2: Lock the loop (but then we will probably end in a deadlock)
> Solution #3: Avoid removing objects right away. Always remove the objects at some defined point.

I could implement solution 1. but I guess that's not preferable because of bad performance.
For 3. I would need a clarification on where the objects should be removed. (Im not too much into the GameLoop yet)

**Comment by danil179** [comment]
I think that solution #1 will not cause such bad performance. You can try to compare it with the CPU percentage wasted on this loop before & after.

**Comment by superewald** [comment]
> I think that solution #1 will not cause such bad performance. You can try to compare it with the CPU percentage wasted on this loop before & after.

You were right, no noticeable performance drops :)
