### ISSUE TITLE
crash when casting garen e

### ISSUE THREAD

**Issue by superewald** [LeagueSandbox/GameServer#990]
The GameServerConsole crahes when casting Garen E.

## Details
`System.NullReferenceException: 'Object reference not set to an instance of an object.'`
https://github.com/LeagueSandbox/GameServer/blob/029c22dcd609a0bb8809e5ac0441119017bcd702/GameServerLib/GameObjects/Spells/Buff.cs#L45

**Comment by danil179** [comment]
Need to add `BuffAddType` to GarenE.
